[versions]
# Minecraft expectations
paperApi = "1.21-R0.1-SNAPSHOT"
fastutil = "8.5.15"
guava = "33.3.1-jre"
log4j = "2.24.1"
gson = "2.11.0"
snakeyaml = "2.2"

# Plugins
dummypermscompat = "1.10"
worldguard-bukkit = "7.0.14"
griefprevention = "18.0.0"
griefdefender = "2.1.0-SNAPSHOT"
residence = "6.0.0.1"
towny = "0.102.0.2"
plotsquared = "7.5.11"

# Third party
bstats = "3.1.0"
sparsebitset = "1.3"
parallelgzip = "1.0.5"
adventure = "4.26.1"
checkerqual = "3.52.1"
truezip = "6.8.4"
auto-value = "1.11.1"
jsr305 = "3.0.2"
rhino-runtime = "1.7.15.1"
zstd-jni = "1.4.8-1" # Not latest as it can be difficult to obtain latest ZSTD libs
antlr4 = "4.13.2"
json-simple = "1.1.1"
jlibnoise = "1.0.0"
jchronic = "0.2.4a"
lz4-java = "1.10.2"
commons-cli = "1.11.0"
paperLib = "1.0.8"
paster = "1.1.7"
vault = "1.7.1"
serverlib = "2.3.7"
linbus = "0.2.0"
autoService = "1.1.1"

## Internal
text-adapter = "3.0.6"
text = "3.0.4"
piston = "0.5.10"

# Tests
mockito = "5.21.0"
junit = "6.0.1"

# Gradle plugins
pluginyml = "0.6.0"
mod-publish-plugin = "1.1.0"
grgit = "5.3.3"
shadow = "9.3.0"
paperweight = "2.0.0-SNAPSHOT"
codecov = "0.2.0"


jqwik = "1.9.3"

# Minimum versions we apply to make dependencies support newer Java
minimumAsm = "9.7"
minimumJdependency = "2.10"
#minimumTinyRemapper = "0.8.11"


[libraries]
# Gradle plugins
grgit = { group = "org.ajoberstar.grgit", name = "grgit-gradle", version.ref = "grgit" }
shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
paperweight = { group = "io.papermc.paperweight.userdev", name = "io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweight" }

# Minecraft expectations
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
log4j-bom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }

# Plugins
dummypermscompat = { group = "com.sk89q", name = "dummypermscompat", version.ref = "dummypermscompat" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "worldguard-bukkit" }
griefprevention = { group = "com.github.TechFortress", name = "GriefPrevention", version.ref = "griefprevention" }
griefdefender = { group = "com.griefdefender", name = "api", version.ref = "griefdefender" }
residence = { group = "com.github.Zrips", name = "Residence", version.ref = "residence" }
towny = { group = "com.palmergames.bukkit.towny", name = "towny", version.ref = "towny" }
plotsquared-core = { group = "com.intellectualsites.plotsquared", name = "plotsquared-core", version.ref = "plotsquared" }
plotsquared-bukkit = { group = "com.intellectualsites.plotsquared", name = "plotsquared-bukkit", version.ref = "plotsquared" }

# Third Party
bstats-base = { group = "org.bstats", name = "bstats-base", version.ref = "bstats" }
bstats-bukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
sparsebitset = { group = "com.zaxxer", name = "SparseBitSet", version.ref = "sparsebitset" }
parallelgzip = { group = "org.anarres", name = "parallelgzip", version.ref = "parallelgzip" }
trueZip = { group = "de.schlichtherle", name = "truezip", version.ref = "truezip" }
autoValue = { group = "com.google.auto.value", name = "auto-value", version.ref = "auto-value" }
autoValue-annotations = { group = "com.google.auto.value", name = "auto-value-annotations", version.ref = "auto-value" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
rhino = { group = "org.mozilla", name = "rhino-runtime", version.ref = "rhino-runtime" }
zstd = { group = "com.github.luben", name = "zstd-jni", version.ref = "zstd-jni" }
antlr4 = { group = "org.antlr", name = "antlr4", version.ref = "antlr4" }
antlr4-runtime = { group = "org.antlr", name = "antlr4-runtime", version.ref = "antlr4" }
json-simple = { group = "com.googlecode.json-simple", name = "json-simple", version.ref = "json-simple" }
jlibnoise = { group = "com.sk89q.lib", name = "jlibnoise", version.ref = "jlibnoise" }
jchronic = { group = "com.sk89q", name = "jchronic", version.ref = "jchronic" }
lz4Java = { group = "at.yawk.lz4", name = "lz4-java", version.ref = "lz4-java" }
commonsCli = { group = "commons-cli", name = "commons-cli", version.ref = "commons-cli" }
paperLib = { group = "io.papermc", name = "paperlib", version.ref = "paperLib" }
adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureMiniMessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
paster = { group = "com.intellectualsites.paster", name = "Paster", version.ref = "paster" }
vault = { group = "com.github.MilkBowl", name = "VaultAPI", version.ref = "vault" }
serverlib = { group = "dev.notmyfault.serverlib", name = "ServerLib", version.ref = "serverlib" }
checkerqual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerqual" }

autoService = { group = "com.google.auto.service", name = "auto-service", version.ref = "autoService" }

linBus-bom = { group = "org.enginehub.lin-bus", name = "lin-bus-bom", version.ref = "linbus" }
linBus-common = { group = "org.enginehub.lin-bus", name = "lin-bus-common" }
linBus-stream = { group = "org.enginehub.lin-bus", name = "lin-bus-stream" }
linBus-tree = { group = "org.enginehub.lin-bus", name = "lin-bus-tree" }
linBus-format-snbt = { group = "org.enginehub.lin-bus.format", name = "lin-bus-format-snbt" }

# Internal
## Text
kyoriText-adapter-bukkit = { group = "net.kyori", name = "text-adapter-bukkit", version.ref = "text-adapter" }
kyoriText-api = { group = "net.kyori", name = "text-api", version.ref = "text" }
kyoriText-serializer-gson = { group = "net.kyori", name = "text-serializer-gson", version.ref = "text" }
kyoriText-serializer-legacy = { group = "net.kyori", name = "text-serializer-legacy", version.ref = "text" }
kyoriText-serializer-plain = { group = "net.kyori", name = "text-serializer-plain", version.ref = "text" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

jqwik = { group = "net.jqwik", name = "jqwik", version.ref = "jqwik" }

mockito-bom = { group = "org.mockito", name = "mockito-bom", version.ref = "mockito" }
mockito-core = { group = "org.mockito", name = "mockito-core" }
mockito-junit-jupiter = { group = "org.mockito", name = "mockito-core" }

log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }

## Piston
[libraries.piston-core]
module = "org.enginehub.piston:core"
version.ref = "piston"

[libraries.piston-defaultImpl]
module = "org.enginehub.piston:default-impl"
version.ref = "piston"

[libraries.piston-coreAp-annotations]
module = "org.enginehub.piston.core-ap:annotations"
version.ref = "piston"

[libraries.piston-coreAp-processor]
module = "org.enginehub.piston.core-ap:processor"
version.ref = "piston"

[libraries.piston-coreAp-runtime]
module = "org.enginehub.piston.core-ap:runtime"
version.ref = "piston"

[plugins]
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml" }
mod-publish-plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish-plugin" }
codecov = { id = "org.enginehub.codecov", version.ref = "codecov" }
