[versions]
# Minecraft expectations
fastutil = "8.5.6"
log4j = "2.17.1"
guava = "31.0.1-jre"
gson = "2.8.8"

# Platform expectations
paper = "1.18.1-R0.1-SNAPSHOT"

# Plugins
vault = "1.7.1"
dummypermscompat = "1.10"
worldguard-bukkit = "7.0.6"
mapmanager = "1.8.0-SNAPSHOT"
griefprevention = "16.17.1"
griefdefender = "2.1.0-SNAPSHOT"
mcore = "7.0.1"
residence = "4.5._13.1"
towny = "0.97.5.0"
protocollib = "4.7.0"
plotsquared = "6.4.0"
redprotect = "1.9.6"

# Third party
paperlib = "1.0.8-SNAPSHOT"
bstats = "3.0.0"
serverlib = "2.3.1"
paster = "1.1.4"
sparsebitset = "1.2"
parallelgzip = "1.0.5"
adventure = "4.9.3"
truezip = "6.8.4"
auto-value = "1.9"
findbugs = "3.0.2"
rhino-runtime = "1.7.13"
zstd-jni = "1.4.8-1" # Not latest as it can be difficult to obtain latest ZSTD libs
antlr4 = "4.9.3"
json-simple = "1.1.1"
jlibnoise = "1.0.0"
jchronic = "0.2.4a"
lz4-java = "1.8.0"
lz4-stream = "1.0.0"
## Internal
adventure-text-minimessage = "4.2.0-SNAPSHOT"
text-adapter = "3.0.6"
text = "3.0.4"
piston = "0.5.7"

# Tests
mockito = "4.3.1"
checker-qual = "3.21.2"

# Gradle plugins
pluginyml = "0.5.1"

[libraries]
# Minecraft expectations
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
log4j = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4jBom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

#Platform expectations
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

# Plugins
vault = { group = "com.github.MilkBowl", name = "VaultAPI", version.ref = "vault" }
dummypermscompat = { group = "com.sk89q", name = "dummypermscompat", version.ref = "dummypermscompat" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "worldguard-bukkit" }
mapmanager = { group = "com.github.InventivetalentDev", name = "MapManager", version.ref = "mapmanager" }
griefprevention = { group = "com.github.TechFortress", name = "GriefPrevention", version.ref = "griefprevention" }
griefdefender = { group = "com.griefdefender", name = "api", version.ref = "griefdefender" }
mcore = { group = "com.massivecraft", name = "mcore", version.ref = "mcore" }
residence = { group = "com.bekvon.bukkit.residence", name = "Residence", version.ref = "residence" }
towny = { group = "com.github.TownyAdvanced", name = "Towny", version.ref = "towny" }
protocollib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocollib" }
plotsquaredBukkit = { group = "com.plotsquared", name = "PlotSquared-Bukkit", version.ref = "plotsquared" }
plotsquaredCore = { group = "com.plotsquared", name = "PlotSquared-Core", version.ref = "plotsquared" }
redprotect = { group = "net.fabiozumbi12", name = "redprotect", version.ref = "redprotect" }

# Third Party
paperlib = { group = "io.papermc", name = "paperlib", version.ref = "paperlib" }
bstatsBukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
bstatsBase = { group = "org.bstats", name = "bstats-base", version.ref = "bstats" }
serverlib = { group = "dev.notmyfault.serverlib", name = "ServerLib", version.ref = "serverlib" }
paster = { group = "com.intellectualsites.paster", name = "Paster", version.ref = "paster" }
sparsebitset = { group = "com.zaxxer", name = "SparseBitSet", version.ref = "sparsebitset" }
parallelgzip = { group = "org.anarres", name = "parallelgzip", version.ref = "parallelgzip" }
adventure = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureNbt = { group = "net.kyori", name = "adventure-nbt", version.ref = "adventure" }
truezip = { group = "de.schlichtherle", name = "truezip", version.ref = "truezip" }
autoValueAnnotations = { group = "com.google.auto.value", name = "auto-value-annotations", version.ref = "auto-value" }
autoValue = { group = "com.google.auto.value", name = "auto-value", version.ref = "auto-value" }
findbugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "findbugs" }
rhino = { group = "org.mozilla", name = "rhino-runtime", version.ref = "rhino-runtime" }
zstd = { group = "com.github.luben", name = "zstd-jni", version.ref = "zstd-jni" }
antlr4 = { group = "org.antlr", name = "antlr4", version.ref = "antlr4" }
antlr4Runtime = { group = "org.antlr", name = "antlr4-runtime", version.ref = "antlr4" }
jsonSimple = { group = "com.googlecode.json-simple", name = "json-simple", version.ref = "json-simple" }
jlibnoise = { group = "com.sk89q.lib", name = "jlibnoise", version.ref = "jlibnoise" }
jchronic = { group = "com.sk89q", name = "jchronic", version.ref = "jchronic" }
lz4Java = { group = "org.lz4", name = "lz4-java", version.ref = "lz4-java" }
lz4JavaStream = { group = "net.jpountz", name = "lz4-java-stream", version.ref = "lz4-stream" }

# Internal
## Text
adventureTextAdapterBukkit = { group = "net.kyori", name = "text-adapter-bukkit", version.ref = "text-adapter" }
adventureTextMiniMessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure-text-minimessage" }
adventureTextApi = { group = "net.kyori", name = "text-api", version.ref = "text" }
adventureTextSerializerGson = { group = "net.kyori", name = "text-serializer-gson", version.ref = "text" }
adventureTextSerializerLegacy = { group = "net.kyori", name = "text-serializer-legacy", version.ref = "text" }
adventureTextSerializerPlain = { group = "net.kyori", name = "text-serializer-plain", version.ref = "text" }
## Piston
piston = { group = "org.enginehub.piston", name = "core", version.ref = "piston" }
pistonImpl = { group = "org.enginehub.piston", name = "default-impl", version.ref = "piston" }
pistonAnnotations = { group = "org.enginehub.piston.core-ap", name = "annotations", version.ref = "piston" }
pistonProcessor = { group = "org.enginehub.piston.core-ap", name = "processor", version.ref = "piston" }
pistonRuntime = { group = "org.enginehub.piston.core-ap", name = "runtime", version.ref = "piston" }

# Tests
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
checkerqual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checker-qual" }
log4jCore = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }

[plugins]
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml" }
