name: "build"

on: ["pull_request", "push"]
 
jobs:
  build:
    strategy:
      matrix:
        java: ["1.8", "11"]
        os: ["ubuntu-18.04"]
    runs-on: "${{ matrix.os }}"
    steps:
    - name: "Checkout Repository"
      uses: "actions/checkout@v2.3.4"
    - name: "Setup JDK ${{ matrix.java }}"
      uses: "actions/setup-java@v1.4.3"
      with:
          java-version: "${{ matrix.java }}"
    - name: "Cache Gradle"
      uses: "actions/cache@v2.1.3"
      with:
        path: |
          "~/.gradle/caches"
          "~/.gradle/wrapper"
        key: "${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle*') }}"
        restore-keys: |
          "${{ runner.os }}-${{ matrix.java }}-gradle-"
    - name: "Cache Local Maven Repository"
      uses: "actions/cache@v2.1.3"
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}"
        restore-keys: |
          "${{ runner.os }}-${{ matrix.java }}-maven-"
    - name: "Cache BuildTools Decompiled Code"
      uses: "actions/cache@v2.1.3"
      with:
        path: "$GITHUB_WORKSPACE/work"
        key: "${{ runner.os }}-buildtools"
        restore-keys: |
          "${{ runner.os }}-buildtools"
    - name: "Test Enviornment"
      run: "echo $GITHUB_WORKSPACE"
    - name: "Download BuildTools"
      run: "wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"
    - name: "Run BuildTools"
      run: "java -jar BuildTools.jar --rev 1.16.5"
    - name: "Clean Build"
      run: "./gradlew clean build sourcesJar javadocJar"
      
