name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.4.0"
      - name : "Validate Gradle Wrapper"
        uses : "gradle/wrapper-validation-action@v1.0.4"
      - name: "Setup Java"
        uses: "actions/setup-java@v2.3.1"
        with:
          distribution: "temurin"
          cache: 'gradle'
          java-version: "17"
      - name: "Clean Build"
        run: "./gradlew clean build --no-daemon"
      - name: "Determine release status"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
      - name: "Publish Release"
        if: "${{ runner.os == 'Linux' && env.STATUS == 'release' && github.event_name == 'push' && github.ref == 'refs/heads/major/2.0.0/1.18'}}"
        run: "./gradlew publishToSonatype closeSonatypeStagingRepository"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.SIGNING_PASSWORD }}"
      - name: "Publish Snapshot"
        if: "${{ runner.os == 'Linux' && env.STATUS != 'release' && github.event_name == 'push' && github.ref == 'refs/heads/major/2.0.0/1.18' }}"
        run: "./gradlew publishToSonatype"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
      - name: "Archive Artifacts"
        uses: "actions/upload-artifact@v2.2.4"
        with:
          name: "FastAsyncWorldEdit-Bukkit-SNAPSHOT"
          path: "worldedit-bukkit/build/libs/FastAsyncWorldEdit-Bukkit-*.jar"
