name: Build PR
on: [pull_request]
jobs:
  build_pr:
    if: github.repository_owner == 'IntellectualSites'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21, 25]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          cache: gradle
          java-version: ${{ matrix.java }}
      - name: Build on Java ${{ matrix.java }}
        run: ./gradlew build -s
      - name: Archive artifacts
        if: ${{ matrix.java == 21 }}
        uses: actions/upload-artifact@v6
        with:
            name: FastAsyncWorldEdit-SNAPSHOT
            path: worldedit-bukkit/build/libs/FastAsyncWorldEdit-*.jar
