name: Java CI

on:
  push:
    branches:
    - '1.15'
  pull_request:
    branches:
    - '1.15'
 
jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Download BuildTools
      run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - name: Run BuildTools
      run: java -jar BuildTools.jar --rev latest
    - name: Test with Gradle
      run: ./gradlew clean build -x test
      
